# -*- coding: utf-8 -*-
"""per3_repost_latihan4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# 4. Class Garis

# titik dibentuk posisi pada sumbu x dan y
class Titik:
  def __init__(self,x,y):
    self.x = x
    self.y = y

# garis dibentuk dari dua titik
class Garis:
  def __init__(self,titik_pertama,titik_kedua):
    self.titik_pertama = titik_pertama
    self.titik_kedua = titik_kedua

  def panjang(self):
    pjg_x = self.titik_kedua.x - self.titik_pertama.x
    pjg_y = self.titik_kedua.y - self.titik_pertama.y
    pjg = (pjg_x**2 + pjg_y**2) ** 0,5
    return pjg

titik_a = Titik(0,0)
Titik_b = Titik(3,4)
garis_ab = Garis(titik_a,titik_b)
print('panjang garis ab adalah {}'.format(garis_ab.panjang()))