# -*- coding: utf-8 -*-
"""per3_repost_latihan2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# 2. Class Titik

class Titik:
  def __init__(self,x,y):
    self.x = x
    self.y = y

titik_a = Titik(0,0)
titik_b = Titik(3,4)
print('Titik A memiliki koordinat ({},{})'.format(titik_a.x,titik_a.y))
print('Titik B memiliki koordinat ({},{})'.format(titik_b.x,titik_b.y))