# -*- coding: utf-8 -*-
"""per3_repost_latihan3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# 3. Class Buku

class Buku: 
  def __init__(self,judul,pengarang,tahun_terbit):
    self.judul = judul 
    self.pengarang = pengarang
    self.tahun_terbit = tahun_terbit

buku = Buku('Tenggelamnya Kapal Van Wijck','HAMKA',1938)
t = 'buku {} karangan {} pertman kali diterbitkan tahun {}' .format(buku.judul,buku.pengarang,buku.tahun_terbit)
print(t)