# -*- coding: utf-8 -*-
"""per4_repost_latihan7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# 7. class pegawai

class Pegawai:
  __nama=""
  __alamat=""
  __gaji=0
  def __init__(self,nama,alamat):
    self.__nama=nama
    self.__alamat=alamat
  def __hitungGaji(self):
    upahLembur=20000
    gajiPokok=3000000
    jumLembur=int(input("Total jam lembur: "))
    self.__gaji=(upahLembur*jumLembur)+gajiPokok
  def tampilDetail(self):
    print("\n--Menghitung dan Menampilkan Detail Gaji Pegawai--")
    print("nama: ", self.__nama)
    print("alamat: ", self.__alamat)
    self.__hitungGaji()
    print("total gaji: ", self.__gaji)
pgw1=Pegawai("Eren yaeger","nganjuk")
pgw1.tampilDetail()
pgw2=Pegawai("Rias gremaory","bandung")
pgw2.tampilDetail()