# -*- coding: utf-8 -*-
"""per4_repost_latihan2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# 2. class utama

class utama:
  def __init__(self):
    self._a = 2
class turunan(utama):
  def __init__(self):
    utama.__init__(self)
    print("memanggil variable protected pada class utama: ",self._a)
    self._a = 3
    print("memanggil variable protected yang dimodifikasi diluar class: ",self._a)
objek1 = turunan()
objek2 = utama()
print("memanggil variable protected dari objek1: ", objek1._a)
print("memanggil variable protected dari objek2: ", objek2._a)