# -*- coding: utf-8 -*-
"""per4_repost_latihan4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# 4. class mobil (public)

#variabel bersifat public
class Mobil():
  def __init__(self,jendela,pintu,mesin):
    self.jendela=jendela
    self.pintu=pintu
    self.mesin=mesin