# -*- coding: utf-8 -*-
"""per4_repost_latihan5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# 5. class mobil(protected)

#variabel bersifat protected
class Mobil():
  def __init__(self,jendela,pintu,mesin):
    self._jendela=jendela
    self._pintu=pintu
    self._mesin=mesin

class Truk(Mobil):
  def __init__(self,jendela,pintu,mesin,tipe):
    super().__init__(jendela,pintu,mesin)
    self.tipebak=tipe