# -*- coding: utf-8 -*-
"""per4_repost_latihan3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# 3. class hitung

class Hitung:
  def __init__(self):
    self. __angkaRahasia = 0
  def tampilkanHitung(self):
    self. __angkaRahasia += 1
    print (self. __angkaRahasia)
hitungan=Hitung()
hitungan.tampilkanHitung()

hitungan.tampilkanHitung()

hitungan._Hitung__angkaRahasia