# -*- coding: utf-8 -*-
"""per5_repost_tugas1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# 1. Multilevel Inheritance
class ComputerPart:
    def __init__(self, pabrikan, nama, harga,jenis):
        self.pabrikan = pabrikan
        self.nama = nama
        self.harga = harga
        self.jenis = jenis


class Processor(ComputerPart):
    def __init__(self, pabrikan, nama, harga):
        self.pabrikan = pabrikan
        self.nama = nama
        self.harga = harga

    def Tampil(self):
        print(
            f"{self.nama} produk dari {self.pabrikan} dijual dengan harga Rp.{self.harga}")


class RandomAccessMemory(Processor):
    def __init__(self, pabrikan, nama, harga, kapasitas):
        self.pabrikan = pabrikan
        self.nama = nama
        self.harga = harga
        self.kapasitas = kapasitas

    def Tampil(self):
        print(
            f"{self.nama} produk dari {self.pabrikan} memiliki kapasitas sebesar {self.kapasitas} dijual dengan harga Rp.{self.harga}")


class HardDiskSATA(RandomAccessMemory):
    def __init__(self, pabrikan, nama, harga):
        self.pabrikan = pabrikan
        self.nama = nama
        self.harga = harga

    def Tampil(self):
        print(
            f"{self.nama} produk dari perusahaan {self.pabrikan} dijual dengan harga Rp.{self.harga}")


pro = Processor('AMD', 'Ryzen™ 7 5800X', 6500000)
ram = RandomAccessMemory('Corsair', 'Corsair Vengeance DDR4 Dimm PC4-28800/3600MHz',1500000,"2x8GB")
hdd = HardDiskSATA('WD Black', 'WD Black Caviar Dekstop HDD 3.5 inch', 2950000)

parts = [pro, ram, hdd]
print("\n\t\t\tMULTILEVEL COMPUTER PART")
print("=================================================================================")
for part in parts:
    part.Tampil()
print("=================================================================================\n")