# -*- coding: utf-8 -*-
"""per6_tugas2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
def rupiah(uang) :
    x = str(uang)
    if len(x) <= 3 :
        return "Rp." + x
    else :
        a = x[:-3]
        b = x[-3:]
        return rupiah(a) + '.' + b
class ComputerPart:
    def __init__(self, pabrikan, nama, harga) :
        self.pabrikan = pabrikan
        self.nama = nama 
        self.harga = harga

class Processor(ComputerPart) :
    def __init__(self, pabrikan, nama, harga) :
        self.pabrikan = pabrikan
        self.nama = nama
        self.harga = harga
    def override(self) : 
        print("Processor")
        print(f"{self.nama} produk dari {self.pabrikan}")
        print(f"Harga\t\t: {rupiah(self.harga)}")          


class RandomAccessMemory(ComputerPart) :
    def __init__(self, pabrikan, nama, harga, kapasitas):
      super().__init__(pabrikan, nama, harga)
      self.kapasitas = kapasitas
    # Override  Method
    def override(self) : 
        print("RandomAccessMemory")
        print(f"{self.nama} produk dari {self.pabrikan}")
        print(f"Kapasitas\t: {self.kapasitas}")
        print(f"Harga\t\t: {rupiah(self.harga)}")
    
class HardDiskSATA(ComputerPart) :
    def __init__(self, pabrikan, nama, harga, kapasitas, rpm) :
      super().__init__(pabrikan, nama, harga)
      self.kapasitas = kapasitas
      self.rpm = rpm 
    # Override  Method
    def override(self) :
        print("HardDiskSATA")
        print(f"{self.nama} produk dari {self.pabrikan}")
        print(f"Kapasitas\t: {self.kapasitas}")
        print(f"RPM\t\t: {self.rpm}")
        print(f"Harga\t\t: {rupiah(self.harga)}")

pro = Processor('Intel', 'Core i7 7740X', 4350000)
ram = RandomAccessMemory('V-Gen', 'DDR4 SODimm PC19200/2400MHz', 328000, '4GB')
hdd = HardDiskSATA('Seagate', 'HDD 2.5 inch', 295000, '500GB', 7200)

print("\n\t\t\tOVERRIDING COMPUTER PART")
print("=================================================================================")
pro.override()
ram.override()
hdd.override()
print("=================================================================================\n")