# -*- coding: utf-8 -*-
"""per6_tugas1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
def rupiah(uang) :
    x = str(uang)
    if len(x) <= 3 :
        return "Rp." + x
    else :
        a = x[:-3]
        b = x[-3:]
        return rupiah(a) + '.' + b
class ComputerPart:
    def __init__(self, pabrikan, nama, jenis, harga) :
        self.pabrikan = pabrikan
        self.nama = nama 
        self.jenis = jenis
        self.harga = harga

class Processor(ComputerPart) :
    def __init__(self, pabrikan, nama, harga) :
        self.pabrikan = pabrikan
        self.nama = nama
        self.harga = harga
              
    def overload(self) :
        print("\nProcessor")
        print(f"{self.nama} produk dari {self.pabrikan}")
        print(f"Harga\t\t: {rupiah(self.harga)}")

class RandomAccessMemory(ComputerPart) :
    def __init__(self, pabrikan, nama, harga):
      self.pabrikan = pabrikan
      self.nama = nama
      self.harga = harga
      #overload method
    def overload(self, kapasitas) : 
      print("\nRandomAccessMemory")
      print(f"{self.nama} produk dari {self.pabrikan}")
      print(f"Kapasitas\t: {kapasitas}")
      print(f"Harga\t\t: {rupiah(self.harga)}")
    
class HardDiskSATA(ComputerPart) :
    def __init__(self, pabrikan, nama, harga) :
      self.pabrikan = pabrikan
      self.nama = nama
      self.harga = harga
    #Overload Method
    def overload(self, kapasitas, rpm) : 
        print("\nHardDiskSATA")
        print(f"{self.nama} produk dari {self.pabrikan}")
        print(f"Kapasitas\t: {kapasitas}")
        print(f"RPM\t\t: {rpm}")
        print(f"Harga\t\t: {rupiah(self.harga)}")

pro = Processor('Intel', 'Core i7 7740X', 4350000)
ram = RandomAccessMemory('V-Gen', 'DDR4 SODimm PC19200/2400MHz', 328000)
hdd = HardDiskSATA('Seagate', 'HDD 2.5 inch', 295000)

print("\n\t\t\tOVERLOADING COMPUTER PART")
print("=================================================================================")
pro.overload()
ram.overload('4GB')
hdd.overload('500GB', 7200)
print("=================================================================================\n")