# -*- coding: utf-8 -*-
"""per6_latihan2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# Polymorphism dengan Class
class Kucing:
  def __init__(self, nama, umur):
    self.nama = nama
    self.umur = umur

  def bersuara(self):
    print("Meow")
class Dog:
  def __init__(self, nama, umur):
    self.nama = nama
    self.umur = umur
  def bersuara(self):
    print("Guk..guk...")
kucing1 = Kucing("Tom", 3)
anjing1 = Dog("Spike", 4)
for hewan in (kucing1, anjing1):
  hewan.bersuara()