# -*- coding: utf-8 -*-
"""per6_latihan1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pOOcuFjc5KXP3cim5koCfFL4D5PRyCs
"""

"""
Nama : Dimas Bintang Himawan
Nim : 5210411224
"""
# PoLymorphism dengan Fungsi

print(len("Polymorphism"))
print(len([0,1,2,3]))
"""Menggunakan Fungsi len
Output :
12 (Tipe Data String)
4 (Tipe Data List)
"""
# using class
class jerman:
  def ibukota(self):
    print("Berlin adalah ibukota negara Jerman")
class jepang:
  def ibukota(self):
    print("Tokyo adalah ibukota negara Jepang")

negara1 = jerman()
negara2 = jepang()

for country in (negara1,negara2):
  country.ibukota()