# -*- coding: utf-8 -*-
"""Tugas_PBO_5210411224.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MBvJCZXQ8xiABZRzvMAqn0Bmz-GP30pV
"""

#program menghitung luas jajar genjang
alas = int(input("masukkan alas= " ))
tinggi = int(input("masukkan tinggi= " ))
def luasjajargenjang(alas,tinggi):
  luas = alas * tinggi
  return luas
hasil = luasjajargenjang(alas,tinggi)
print("Luas dari jajar genjang tersebut adalah= " + str(hasil)+ "cm")